[package]
name = "tools"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "tools"
path = "src/lib.rs"

[[bin]]
name = "gen_midi"
path = "src/bin/gen_midi.rs"

[[bin]]
name = "gen_sf2"
path = "src/bin/gen_sf2.rs"

[[bin]]
name = "render_wav"
path = "src/bin/render_wav.rs"

[dependencies]
midly = { workspace = true }
rhythm-synth = { path = "../synth" }

[dev-dependencies]
rustysynth = { workspace = true }
